-- MySQL Script generated by MySQL Workbench
-- Tue Oct 12 18:11:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myevents
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myevents
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myevents` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `myevents` ;

-- -----------------------------------------------------
-- Table `myevents`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myevents`.`usuario` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `userMail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phonenumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myevents`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myevents`.`evento` (
  `eventID` INT NOT NULL AUTO_INCREMENT,
  `eventName` VARCHAR(45) NOT NULL,
  `startTime` DATETIME NOT NULL,
  `endTime` DATETIME NOT NULL,
  `available` TINYINT NOT NULL,
  `eventPreference` TINYINT NOT NULL,
  `coordinate` VARCHAR(100) NULL,
  `videomeeting` VARCHAR(100) NULL,
  `userOwner` INT NOT NULL,
  `userSummoner` INT NULL,
  PRIMARY KEY (`eventID`),
  INDEX `userIDOwner_idx` (`userOwner` ASC) VISIBLE,
  INDEX `userIDSummoner_idx` (`userSummoner` ASC) VISIBLE,
  CONSTRAINT `userIDOwner`
    FOREIGN KEY (`userOwner`)
    REFERENCES `myevents`.`usuario` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userIDSummoner`
    FOREIGN KEY (`userSummoner`)
    REFERENCES `myevents`.`usuario` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
